# SAST AI Frontend - Development Environment Overrides

namespace: sast-ai-dev

app:
  image:
    pullPolicy: Always
    tag: "latest"

  env:
    REACT_APP_ORCHESTRATOR_API_URL: "https://sast-ai-orchestrator-sast-ai-dev.apps.appeng.clusters.se-apps.redhat.com/api/v1"
    REACT_APP_WS_URL: "wss://sast-ai-orchestrator-sast-ai-dev.apps.appeng.clusters.se-apps.redhat.com/ws/dashboard"
    REACT_APP_GRAFANA_URL: "http://sast-ai-grafana-service-sast-ai-mlops.apps.appeng.clusters.se-apps.redhat.com/dashboards"
