# SAST AI Frontend - Development Environment Overrides

namespace: sast-ai-dev

consoleLink:
  enabled: false

app:
  env:
    REACT_APP_ORCHESTRATOR_API_URL: "https://sast-ai-orchestrator-sast-ai-dev.apps.appeng.clusters.se-apps.redhat.com/api/v1"
    REACT_APP_WS_URL: "wss://sast-ai-orchestrator-sast-ai-dev.apps.appeng.clusters.se-apps.redhat.com/ws/dashboard"
